**Prerequisites:**

This tutorial series is for you if you're just getting started with data science and deep learning. 
You only need to be aware of the following:
* Python Programming Fundamentals (variables, data types, loops, functions etc.)

* Some math from high school (vectors, matrices, derivatives and probability)
* It is not necessary to have any prior expertise of data science or deep learning.




In [ ]:
import torch

In [ ]:
t1=torch.tensor(4.0)
t1

tensor(4.)

In [ ]:
t1.dtype, t1.shape

(torch.float32, torch.Size([]))

In [ ]:
t2=torch.tensor([1.0,2,3,4,5,6,7,8,9])

In [ ]:
t2.dtype, t2.shape

(torch.float32, torch.Size([9]))

In [ ]:
t3=torch.tensor([
                 [[11,12,12],
                  [1,2,2],
                  ],
                 [
                  [1,2,2],
                  [1,2,2],],
                 ]
                )

t3

tensor([[[11, 12, 12],
         [ 1,  2,  2]],

        [[ 1,  2,  2],
         [ 1,  2,  2]]])

In [ ]:
t3.dtype, t3.shape

(torch.int64, torch.Size([2, 2, 3]))

# Tensor operations

In [ ]:
#y=wx+b
x=torch.tensor(3.)
w=torch.tensor(4., requires_grad=True)
b=torch.tensor(7.0,requires_grad=True)

In [ ]:
y=w*x+b
y

tensor(19., grad_fn=<AddBackward0>)

In [ ]:
y.backward()

In [ ]:
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


# numpy operation

In [ ]:
import numpy as np

arr=np.array([ [1,2],[2,3]          
               ])

arr.shape , arr.dtype

((2, 2), dtype('int64'))

In [ ]:
y=torch.from_numpy(arr)
y

tensor([[1, 2],
        [2, 3]])

In [ ]:
y.dtype,y.shape

(torch.int64, torch.Size([2, 2]))

In [ ]:
z=torch.tensor(arr)
z

tensor([[1, 2],
        [2, 3]])

In [ ]:
#z is  differen mem location by copying value and from numpy on is same mem location

In [ ]:
# torch to numpy 
nz=z.numpy()
nz

array([[1, 2],
       [2, 3]])

In [ ]:
x=torch.tensor([3.,6,7])
w=torch.tensor([4.,5,6] ,requires_grad=True)
b=torch.tensor([7.0,11,123],requires_grad=True)
##y=(w*x+b)
y=(w*x+b).sum()
print(y)
y.backward()
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

tensor(225., grad_fn=<SumBackward0>)
dy/dx None
dy/dw tensor([3., 6., 7.])
dy/db tensor([1., 1., 1.])


In [ ]:
2+2

4

# Linear Regression with PYTORCH

In [ ]:
import numpy as np
import torch

In [ ]:
inputs=np.array([
                 [73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]
],dtype="float32")

In [ ]:
targets=np.array([
                  [56,70],
                  [81,101],
                  [199,113],
                  [22,37],
                  [103,119]
                  ],dtype="float32")

In [ ]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [ ]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w,b)

tensor([[-1.0690, -1.0524, -0.3828],
        [ 0.9188,  2.1762,  0.6692]], requires_grad=True) tensor([0.1241, 1.4352], requires_grad=True)


In [ ]:
def model(x):
  return x @ w.t() + b


In [ ]:
preds=model(inputs)
print(preds)

tensor([[-164.8870,  243.0858],
        [-214.2694,  319.3768],
        [-256.1068,  411.7927],
        [-168.3336,  213.4853],
        [-201.4674,  320.5891]], grad_fn=<AddBackward0>)


In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [199., 113.],
        [ 22.,  37.],
        [103., 119.]])


# Loss functions

In [ ]:
diff=targets-preds
diff

tensor([[ 220.8870, -173.0858],
        [ 295.2693, -218.3768],
        [ 455.1068, -298.7927],
        [ 190.3336, -176.4853],
        [ 304.4674, -201.5891]], grad_fn=<SubBackward0>)

In [ ]:
def mse ( t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [ ]:
loss=mse(preds,targets)
loss

tensor(71073.3906, grad_fn=<DivBackward0>)

In [ ]:
#compute grads
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[-1.0690, -1.0524, -0.3828],
        [ 0.9188,  2.1762,  0.6692]], requires_grad=True)
tensor([[-24602.1660, -27836.1328, -16629.3281],
        [ 18082.7324,  19558.7090,  11877.9941]])


In [ ]:
print(b)
print(b.grad)

tensor([0.1241, 1.4352], requires_grad=True)
tensor([-293.2128,  213.6659])


In [ ]:
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
preds=model(inputs)
print(preds)
loss=mse(preds,targets)
loss

tensor([[-121.1237,  211.6714],
        [-156.7399,  278.1058],
        [-187.7546,  362.9608],
        [-125.1141,  182.2337],
        [-146.1257,  281.0189]], grad_fn=<AddBackward0>)


tensor(48243.8867, grad_fn=<DivBackward0>)

# Multiple epochs

In [ ]:
for i in range(1,100):
  preds=model(inputs)
  loss=mse(preds,targets)
  print('epch no :',i,', loss :',loss)
  loss.backward()
  with torch.no_grad():

    w-=w.grad*1e-4
    b-=b.grad*1e-4
    w.grad.zero_()
    b.grad.zero_()




epch no : 1 , loss : tensor(48243.8867, grad_fn=<DivBackward0>)
epch no : 2 , loss : tensor(30496.1816, grad_fn=<DivBackward0>)
epch no : 3 , loss : tensor(19369.2812, grad_fn=<DivBackward0>)
epch no : 4 , loss : tensor(12387.0176, grad_fn=<DivBackward0>)
epch no : 5 , loss : tensor(7999.9961, grad_fn=<DivBackward0>)
epch no : 6 , loss : tensor(5238.6357, grad_fn=<DivBackward0>)
epch no : 7 , loss : tensor(3496.1118, grad_fn=<DivBackward0>)
epch no : 8 , loss : tensor(2392.5820, grad_fn=<DivBackward0>)
epch no : 9 , loss : tensor(1690.2236, grad_fn=<DivBackward0>)
epch no : 10 , loss : tensor(1240.0853, grad_fn=<DivBackward0>)
epch no : 11 , loss : tensor(948.8353, grad_fn=<DivBackward0>)
epch no : 12 , loss : tensor(757.9542, grad_fn=<DivBackward0>)
epch no : 13 , loss : tensor(630.7179, grad_fn=<DivBackward0>)
epch no : 14 , loss : tensor(544.0514, grad_fn=<DivBackward0>)
epch no : 15 , loss : tensor(483.4293, grad_fn=<DivBackward0>)
epch no : 16 , loss : tensor(439.6880, grad_fn=<Di

In [ ]:
  preds=model(inputs)
  loss=mse(preds,targets)
  print(preds , loss)

tensor([[ 69.2721,  67.8536],
        [ 88.8265,  96.1444],
        [183.1737, 122.4538],
        [ 12.5931,  40.7109],
        [111.2445, 111.1819]], grad_fn=<AddBackward0>) tensor(83.6787, grad_fn=<DivBackward0>)


# LR with Pytorch built ins 

In [ ]:
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')


In [ ]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [ ]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  print('batch')

tensor([[ 87., 135.,  57.],
        [ 73.,  66.,  44.],
        [ 91.,  87.,  65.],
        [ 68.,  96.,  71.],
        [ 88., 134.,  59.]])
tensor([[118., 134.],
        [ 57.,  69.],
        [ 80., 102.],
        [104., 118.],
        [118., 132.]])
batch
tensor([[ 92.,  87.,  64.],
        [ 74.,  66.,  43.],
        [ 73.,  67.,  43.],
        [ 68.,  97.,  70.],
        [101.,  44.,  37.]])
tensor([[ 82., 100.],
        [ 57.,  69.],
        [ 56.,  70.],
        [102., 120.],
        [ 21.,  38.]])
batch
tensor([[102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [103.,  43.,  36.]])
tensor([[ 22.,  37.],
        [ 81., 101.],
        [119., 133.],
        [103., 119.],
        [ 20.,  38.]])
batch


In [ ]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5312, -0.4376, -0.1538],
        [-0.2619, -0.5629, -0.1817]], requires_grad=True)
Parameter containing:
tensor([-0.5644,  0.0908], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.5312, -0.4376, -0.1538],
         [-0.2619, -0.5629, -0.1817]], requires_grad=True),
 Parameter containing:
 tensor([-0.5644,  0.0908], requires_grad=True)]

In [ ]:
preds=model(inputs)
preds

tensor([[ -75.2773,  -64.5573],
        [ -97.2588,  -84.9085],
        [-114.3432, -108.6652],
        [ -79.2564,  -57.5527],
        [ -89.9959,  -84.7398],
        [ -75.3709,  -64.2563],
        [ -96.9750,  -84.5273],
        [-115.0281, -109.1088],
        [ -79.1628,  -57.8537],
        [ -89.6185,  -84.6596],
        [ -74.9934,  -64.1761],
        [ -97.3524,  -84.6075],
        [-114.6270, -109.0465],
        [ -79.6338,  -57.6329],
        [ -89.9024,  -85.0408]], grad_fn=<AddmmBackward>)

In [ ]:
import torch.nn.functional as F

In [ ]:
loss_fn=F.mse_loss

In [ ]:
loss=loss_fn(model(inputs),targets)
loss

tensor(31220.6387, grad_fn=<MseLossBackward>)

In [ ]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [ ]:
def fit (num_epochs,model,loss_fn,opt):
  for epoch in range (0,num_epochs):
    for xb,yb in train_dl:
      preds=model(xb)
      loss=loss_fn(preds,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if(epoch+1)%10==0:
      print('Epoch [{}/{}], Loss : {:.4f}'.format(epoch+1,num_epochs,loss.item()))

In [ ]:
fit(100,model,loss_fn,opt)

Epoch [10/100], Loss : 221.5063
Epoch [20/100], Loss : 649.3920
Epoch [30/100], Loss : 157.0114
Epoch [40/100], Loss : 80.5985
Epoch [50/100], Loss : 10.4192
Epoch [60/100], Loss : 49.8885
Epoch [70/100], Loss : 47.5153
Epoch [80/100], Loss : 30.7400
Epoch [90/100], Loss : 17.0009
Epoch [100/100], Loss : 22.2958


In [ ]:
preds=model(inputs)
preds

tensor([[ 57.9064,  71.7748],
        [ 81.3214,  98.8958],
        [118.1050, 134.1028],
        [ 26.9114,  45.5871],
        [ 96.9696, 111.1065],
        [ 56.7965,  70.8431],
        [ 80.9822,  98.6192],
        [118.3398, 134.5511],
        [ 28.0214,  46.5188],
        [ 97.7404, 111.7616],
        [ 57.5673,  71.4982],
        [ 80.2114,  97.9641],
        [118.4441, 134.3794],
        [ 26.1406,  44.9321],
        [ 98.0795, 112.0382]], grad_fn=<AddmmBackward>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])